models/AbsenDosen.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "dynamic_absen_dosen".
 *
 * @property int $id ID
 * @property string|null $dosen_id Dosen
 * @property int|null $kelas_id Kelas
 * @property string|null $occurred_at Tanggal
 * @property string|null $hour_start Jam Mulai
 * @property string|null $hour_end Jam Selesai
 * @property string|null $theory Materi
 * @property int|null $conference_for Tatap Muka ke
 *
 * @property Kelas $kelas
 * @property Dosen $dosen
 * @property AbsenMahasiswa[] $AbsenMahasiswas
 */
class AbsenDosen extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'dynamic_absen_dosen';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['id'], 'required'],
            [['id', 'kelas_id', 'conference_for'], 'integer'],
            [['occurred_at', 'hour_start', 'hour_end'], 'safe'],
            [['theory'], 'string'],
            [['dosen_id'], 'string', 'max' => 255],
            [['id'], 'unique'],
            [['kelas_id'], 'exist', 'skipOnError' => true, 'targetClass' => Kelas::className(), 'targetAttribute' => ['kelas_id' => 'id']],
            [['dosen_id'], 'exist', 'skipOnError' => true, 'targetClass' => Dosen::className(), 'targetAttribute' => ['dosen_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'dosen_id' => 'Dosen',
            'kelas_id' => 'Kelas',
            'occurred_at' => 'Tanggal',
            'hour_start' => 'Jam Mulai',
            'hour_end' => 'Jam Selesai',
            'theory' => 'Materi',
            'conference_for' => 'Tatap Muka ke',
        ];
    }

    /**
     * Gets query for [[Kelas]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getKelas()
    {
        return $this->hasOne(Kelas::className(), ['id' => 'kelas_id']);
    }

    /**
     * Gets query for [[Dosen]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getDosen()
    {
        return $this->hasOne(Dosen::className(), ['id' => 'dosen_id']);
    }

    /**
     * Gets query for [[AbsenMahasiswas]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getAbsenMahasiswas()
    {
        return $this->hasMany(AbsenMahasiswa::className(), ['absen_dosen_id' => 'id']);
    }
}

controllers/AbsenDosenController.php
<?php

namespace app\controllers;

use Yii;

use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
use PhpOffice\PhpSpreadsheet;
use yii\web\NotFoundHttpException;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\AbsenDosen;
use app\models\KalenderAkademik;
use app\models\Kelas;
use app\models\Prodi;

/**
 * AbsenController implements the CRUD actions for AbsenDosen model.
 */
class AbsenDosenController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all AbsenDosen models.
     * @return mixed
     */
    public function actionIndex()
    {
        $day  = ['senin', 'selasa', 'rabu', 'kamis', 'jum\'at'];
        $days = ['Senin', 'Selasa', 'Rabu', 'Kamis', 'Jum\'at']; 

        if (\Yii::$app->request->isPost) {
            $ka     = $_POST['Kelas']['ka_id'];
            $prodi  = $_POST['Kelas']['prodi_id'];
            $mk     = $_POST['Kelas']['mk_id'];
        
            for ($i = 0; $i < count($day); $i++) {
                $query = Kelas::find()->where(['day' => $day[$i]]);
                $query->andFilterWhere([
                    'ka_id' => $ka,
                    'prodi_id' => $prodi,
                    'mk_id' => $mk,
                ]);
                $dataProvider[$i] = new ActiveDataProvider([
                    'query' => $query,
                    'pagination' => false,
                ]);
            } 

            $ka = KalenderAkademik::findOne($ka)->name;
            $prodi = Prodi::findOne($prodi)->name;

            $model = new Kelas();

            return $this->render('index', [
                'dataProviders' => $dataProvider,
                'model' => $model,
                'day' => $days,
                'ka' => $ka,
                'prodi' => $prodi
            ]);
        }

        else {
            for ($i = 0; $i < count($day); $i++) {
                $dataProvider[$i] = new ActiveDataProvider([
                    'query' => Kelas::find()->where(['day' => $day[$i]]),
                    'pagination' => false,
                ]);
            }
        }

        $model = new Kelas();

        return $this->render('index', [
            'dataProviders' => $dataProvider,
            'model' => $model,
            'day' => $days,
            'ka' => 'UN',
            'prodi' => 'FILTERED'
        ]);
    }
    
    public function actionExport() 
    {
        $sql = "SELECT d.name AS dosen, mk.name AS mata_kuliah, COUNT(ad.conference_for) AS cf 
                FROM dynamic_absen_dosen ad 
                LEFT OUTER JOIN static_dosen d ON ad.dosen_id = d.id 
                LEFT OUTER JOIN static_kelas k ON ad.kelas_id = k.id
                LEFT OUTER JOIN static_matakuliah mk ON k.mk_id = mk.id
                GROUP BY ad.dosen_id, ad.kelas_id ORDER BY dosen ASC ";

        if (($database = Yii::$app->db->createCommand($sql)->queryAll()) != null) {

            $spreadsheet = new PhpSpreadsheet\Spreadsheet();
            $spreadsheet->setActiveSheetIndex(0);
            $worksheet = $spreadsheet->getActiveSheet();

            $styleBody = array(
                'borders' => array(
                    'outline' => array(
                        'borderStyle' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
                        'color' => array('argb' => '0000000'),
                    ),
                ),
            );

            $styleHeader = [
                'font' => [
                    'bold' => true,
                ],
                'alignment' => [
                    'horizontal' => \PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER,
                ],
                'borders' => array(
                    'outline' => array(
                        'borderStyle' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
                        'color' => array('argb' => '0000000'),
                    ),
                ),
            ];

            $worksheet->setCellValue('A1', 'Nama Dosen');
            $worksheet->setCellValue('B1', 'Mata Kuliah');
            $worksheet->setCellValue('C1', 'presensi');

            $worksheet->getStyle('A1')->applyFromArray($styleHeader);
            $worksheet->getStyle('B1')->applyFromArray($styleHeader);
            $worksheet->getStyle('C1')->applyFromArray($styleHeader);

            $x= 2;

            for($i = 0; $i < count($database); $i++) {
                $worksheet->setCellValue('A'.$x, $database[$i]['dosen']);
                $worksheet->setCellValue('B'.$x, $database[$i]['mata_kuliah']);
                $worksheet->setCellValue('C'.$x, $database[$i]['cf'].'/14');

                $worksheet->getStyle('A'.$x)->applyFromArray($styleBody);
                $worksheet->getStyle('B'.$x)->applyFromArray($styleBody);
                $worksheet->getStyle('C'.$x)->applyFromArray($styleBody);
                $x++;
            }

            foreach ($spreadsheet->getWorksheetIterator() as $worksheet) {

                $spreadsheet->setActiveSheetIndex($spreadsheet->getIndex($worksheet));
            
                $sheet = $spreadsheet->getActiveSheet();
                $cellIterator = $sheet->getRowIterator()->current()->getCellIterator();
                $cellIterator->setIterateOnlyExistingCells(true);
                /** @var PHPExcel_Cell $cell */
                foreach ($cellIterator as $cell) {
                    $sheet->getColumnDimension($cell->getColumn())->setAutoSize(true);
                }
            }

            $writer = new Xlsx($spreadsheet);
            $writer->save('excel/rekap.xls');

            return $this->redirect('download');
        }

        throw new NotFoundHttpException('The requested data does not exist in our record.');
    }

    public function actionDownload()
    {
        Yii::$app->response->sendFile('excel/rekap.xls');
    }

    public function actionThrow()
    {
        throw new NotFoundHttpException("Your request is not supported by our team.");
    }

    /**
     * Displays a single AbsenDosen model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new AbsenDosen model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate($kelas = null, $dosen = null)
    {
        $model = new AbsenDosen();
        $kelasModel = Kelas::findOne($kelas);

        $model->kelas_id = $kelas;
        $model->dosen_id = $dosen;
        $model->hour_start = $kelasModel->start_at;
        $model->hour_end = $kelasModel->end_at;
        $model->occurred_at = date('Y-m-d');

        $sql = "SELECT COUNT(id) AS jml FROM dynamic_absen_dosen ad WHERE dosen_id = '$dosen' AND kelas_id = $kelas";

        if (($database = Yii::$app->db->createCommand($sql)->queryAll()) != null) {
            $cf = $database[0]['jml'];
            $model->conference_for = $cf + 1;
        } else {
            $model->conference_for = 0 + 1;
        }
        if ($model->load(\Yii::$app->request->post())) {
            if ($model->save(false)) {
                return $this->redirect(\Yii::$app->request->referrer ?: \Yii::$app->homeUrl);
            }
        }

        return $this->renderAjax('create', [
            'model' => $model,
        ]);
    }

    /**
     * Finds the AbsenDosen model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return AbsenDosen the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = AbsenDosen::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/absen-dosen/_form.php
<?php

use app\models\Dosen;
use app\models\KalenderAkademik;
use app\models\Kelas;
use app\models\Matakuliah;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\AbsenDosen */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="absen-dosen-form">

    <?php $form = ActiveForm::begin([
    ]); ?>
        <div class="row">
            <div class="col-md-6">
                <label>Mata Kuliah</label>
                <p class="form-group"><?= Matakuliah::findOne(Kelas::findOne($model->kelas_id)->mk_id)->name ?></p>
            </div>
            <div class="col-md-6">
                <label>Semester</label>
                <p class="form-group"><?= KalenderAkademik::findOne(Kelas::findOne($model->kelas_id)->ka_id)->name ?></p>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <label>Tanggal</label>
                <?= $form->field($model, 'occurred_at', [
                    'template' => '{label}<span class="input-group-addon"><i class="fas fa-calendar"></i></span>{input}{error}{hint}',
                    'options' => [
                        'class' => 'input-group'
                    ]
                ])->textInput(['disabled' => true, 'readonly' => true])->label(false) ?>
            </div>
            <div class="col-md-6">
                <?= $form->field($model, 'conference_for')->textInput(['disabled' => true, 'readonly' => true]) ?>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6">
                <label>Jam Mulai</label>
                <?= $form->field($model, 'hour_start', [
                    'template' => '{label}{input}<span class="input-group-btn"><button class="btn btn-info btn-flat"><i class="fas fa-clock"></i></button></span>{error}{hint}',
                    'options' => [
                        'class' => 'input-group'
                    ]
                ])->textInput(['disabled' => true])->label(false) ?>
            </div>
            <div class="col-md-6">
                <div>
                    <label>Jam Akhir</label>
                    <?= $form->field($model, 'hour_end', [
                        'template' => '<div class="input-group">{label}{input}<span class="input-group-btn"><button class="btn btn-info btn-flat"><i class="fas fa-clock"></i></button></span></div>{error}{hint}',
                        'options' => [
                            'class' => 'input-group'
                        ]
                    ])->textInput(['disabled' => true])->label(false) ?>
                </div>
            </div>
        </div>
        <div class="form-group disabled">
            <label>Dosen</label>
            <p class="form-control"><?= Dosen::findOne($model->dosen_id)->name ?></p>
        </div>
        <?= $form->field($model, 'theory')->textarea(['rows' => 6, 'placeholder' => 'Masukan Materi...']) ?>

        <?= $form->field($model, 'dosen_id')->hiddenInput()->label(false) ?>
        <?= $form->field($model, 'kelas_id')->hiddenInput()->label(false) ?>

        <div class="form-group">
            <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
            <?= Html::a('Batal', '/absen-dosen/index', ['class' => 'btn btn-warning']) ?>
        </div>
    <?php ActiveForm::end(); ?>

</div>

views/absen-dosen/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\AbsenDosenSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="absen-dosen-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
        'options' => [
            'data-pjax' => 1
        ],
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'tgl') ?>

    <?= $form->field($model, 'jam_masuk') ?>

    <?= $form->field($model, 'jam_pulang') ?>

    <?= $form->field($model, 'materi') ?>

    <?php // echo $form->field($model, 'tmke') ?>

    <?php // echo $form->field($model, 'kelas_id') ?>

    <?php // echo $form->field($model, 'dosen_id') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <?php // echo $form->field($model, 'created_by') ?>

    <?php // echo $form->field($model, 'updated_by') ?>

    <?php // echo $form->field($model, 'absen_in') ?>

    <?php // echo $form->field($model, 'absen_out') ?>

    <?php // echo $form->field($model, 'bulan_bayar') ?>

    <?php // echo $form->field($model, 'tahun_bayar') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/absen-dosen/create.php
<div class="absen-dosen-create">
    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/absen-dosen/export.php
<?php

use app\models\AbsenDosen;
use app\models\Dosen;
use app\models\Kelas;
use kartik\grid\GridView;

?>
<div>
<?= GridView::widget([
    'dataProvider' => $dataProvider,
    'panel' => false,
    'columns' => [
        ['class' => 'kartik\grid\SerialColumn'],
        [
            'class' => 'kartik\grid\DataColumn',
            'label' => 'Mata Kuliah',
            'value' => function($dataProvider) {
                $ad = AbsenDosen::findOne($dataProvider->id);
                $matkul = $ad->materi;
                $kelas = Kelas::findOne($ad->kelas_id)->name;

                return $matkul;
            },
        ],
        [
            'class' => 'kartik\grid\DataColumn',
            'label' => 'Dosen',
            'value' => function($dataProvider) {
                $ad = AbsenDosen::findOne($dataProvider->id);
                $dosen = Dosen::findOne($ad->kelas_id)->name;

                return $dosen;
            },
        ],
        [
            'class' => 'kartik\grid\DataColumn',
            'label' => 'Presensi',
            'value' => function($dataProvider) {
                $ad = AbsenDosen::findOne($dataProvider->id);
                $tmke = $ad->tmke;
                return "$tmke / 14";
            },
        ],
    ],
]); ?>
</div>

views/absen-dosen/index.php
<?php

use app\models\AbsenDosen;
use app\models\Dosen;
use app\models\KalenderAkademik;
use app\models\Matakuliah;
use app\models\Prodi;
use kartik\select2\Select2;
use yii\bootstrap\ActiveForm;
use yii\helpers\Html;
use yii\grid\GridView;
use yii\bootstrap\ButtonDropdown;
use yii\bootstrap\Modal;
use yii\helpers\ArrayHelper;
/* @var $this yii\web\View */
/* @var $searchModel app\models\AbsenDosenSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Presensi Dosen & Mahasiswa';
$this->params['breadcrumbs'][] = ['label' => 'Akademik', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="absen-dosen-index">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title"><div class="pull-left"><i class="fas fa-clock" style="padding-right: 1rem;"></i></div> Presensi Dosen & Mahasiswa</h3>
        </div>
        <div class="panel-body row">
            <div class="row" style="margin: 2rem 0;">
                <div class="col-md-12">
                    <?php $form = ActiveForm::begin(['layout' => 'inline']) ?>
                        <?= $form->field($model, 'ka_id')->widget(Select2::className(),[
                            'data' => ArrayHelper::map(KalenderAkademik::find()->all(), 'id', 'name'),
                            'options' => [
                                'placeholder' => 'Pilih Kalender Akademik...',
                                'id' => 'ka-id',
                            ]
                        ])->label(false) ?>
                        <?= $form->field($model, 'prodi_id')->widget(Select2::className(),[
                            'data' => ArrayHelper::map(Prodi::find()->all(), 'id', 'abbr'),
                            'options' => [
                                'placeholder' => 'Prodi',
                                'id' => 'prodi-id'
                            ],
                        ])->label(false) ?>
                        <?= $form->field($model, 'mk_id')->widget(Select2::className(),[
                            'data' => ArrayHelper::map(Matakuliah::find()->all(), 'id', 'name'),
                            'options' => [
                                'placeholder' => 'Mata kuliah',
                                'id' => 'mk-id'
                            ],
                        ])->label(false) ?>
                        <div class="form-group">
                            <?= Html::submitButton('Tampilkan Jadwal', ['class'=>'btn btn-primary']) ?>
                        </div>
                        <div class="form-group">
                            <?= Html::a('Reset Jadwal', '/absen-dosen/index', ['class'=>'btn btn-warning']) ?>
                        </div>
                    <?php ActiveForm::end() ?>
                </div>
            </div>
            <div class="row" style="margin: 2rem 0;">
                <div class="col-md-5">
                    <span class="well well-sm label-default" style="padding: .5rem;">
                        <?= $ka . ' - ' . $prodi?>
                    </span>
                </div>
                <div class="col-md-5 pull-right">
                    <div class="pull-right btn-toolbar">
                        <?= ButtonDropdown::widget([
                            'label' => 'Cetak Rekap',
                            'dropdown' => [
                                'items' => [
                                    ['label' => '<i class="fa fa-file-excel" style="color: green;"></i> Excel', 'url' => '/absen-dosen/export'],
                                    ['label' => '<i class="fa fa-file-pdf" style="color: red;"></i> PDF', 'url' => '/absen-dosen/throw'],
                                ],
                                'encodeLabels' => false,
                            ],
                            'options' => [
                                'class' => 'btn btn-sm btn-default'
                            ]
                        ]) ?>
                        <?= Html::a('Cetak Detail Presensi ', '/absen-dosen/throw', ['class'=>'btn btn-sm btn-default']) ?>
                        <?= Html::a('Cetak Presensi Mahasiswa', '/absen-dosen/throw', ['class'=>'btn btn-sm btn-default']) ?>
                    </div>
                </div>
            </div>
            <div style="margin: 2rem 0;">
                <?php $i = 0; ?>
                <?php foreach ($dataProviders as $dataProvider):?>
                    <div class="_tbl">
                    <h3 style="margin-left: .5em;"><?= $day[$i] ?></h3>
                    <?= GridView::widget([
                        'dataProvider' => $dataProvider,
                        'layout' => "{items}\n{pager}",
                        'columns' => [
                            ['class' => 'yii\grid\SerialColumn'],
                            [
                                'class' => 'yii\grid\DataColumn',
                                'label' => 'Jam',
                                'value' => function($dataProvider) {
                                    $jam = implode(' - ', [date('H:i', strtotime($dataProvider->start_at)), date('H:i', strtotime($dataProvider->end_at))]);
                                
                                    return $jam;
                                },
                            ],
                            [
                                'class' => 'yii\grid\DataColumn',
                                'label' => 'Mata Kuliah',
                                'headerOptions' => [
                                    'style' => 'text-align: left;'
                                ],
                                'value' => function($dataProvider) {
                                    $mk = Matakuliah::findOne($dataProvider->mk_id)->name;
                                    $sm = date('Y') - $dataProvider->semester;
                                    $sm = str_split($sm);
                                    $sm = $sm[2] . $sm[3];

                                    if ($dataProvider->prodi_id == 1) {
                                        $prodi = 'TI';
                                    }
                                    if ($dataProvider->prodi_id == 2) {
                                        $prodi = 'SI';
                                    }
                                    $kelas = sprintf('%s%s01', $prodi, $sm);
                                
                                    return "<div style='text-align: left;'>$mk<br><span class='label' style='background-color:#f2dede; color:#c7254e;'>$kelas</span></div>";
                                },
                                'format' => 'html'
                            ],
                            [
                                'class' => 'yii\grid\DataColumn',
                                'label' => 'Semester',
                                'value' => function($dataProvider) {
                                
                                    return $dataProvider->semester;
                                },
                            ],
                            [
                                'class' => 'yii\grid\DataColumn',
                                'label' => 'SKS',
                                'value' => function($dataProvider) {
                                    $sks = Matakuliah::findOne($dataProvider->mk_id)->sks;
                                    $semester = 3; //Kelas::findOne($ad->kelas_id)->;
                                
                                    return $sks;
                                },
                            ],
                            [
                                'class' => 'yii\grid\DataColumn',
                                'label' => 'Dosen',
                                'headerOptions' => [
                                    'style' => 'text-align: left;'
                                ],
                                'contentOptions' => [
                                    'style' => 'text-align: left;'
                                ],
                                'value' => function($dataProvider) {
                                    $dosen = strtolower(Dosen::findOne($dataProvider->dosen_id)->name);
                                
                                    return "<p class='text-capitalize'>$dosen</p>";
                                },
                                'format' => 'raw',
                            ],
                            [
                                'class' => 'yii\grid\DataColumn',
                                'label' => 'Daftar Presensi',
                                'value' => function() {
                                    return '<div class="">'.Html::button('DOSEN', ['class'=>'btn btn-sm btn-default disabled']) .' '. Html::button('KELAS', ['class'=>'btn btn-sm btn-default disabled']) . '</div>';
                                },
                                'format' => 'raw'
                            ],
                            [
                                'class' => 'yii\grid\DataColumn',
                                'label' => 'Presensi',
                                'value' => function($dataProvider) {
                                    $dosen = $dataProvider->dosen_id;
                                    $kelas = $dataProvider->id;
                                    $sql = "SELECT COUNT(id) AS jml FROM dynamic_absen_dosen ad WHERE dosen_id = '$dosen' AND kelas_id = $kelas";
                                    if (($database = Yii::$app->db->createCommand($sql)->queryAll()) != null) {
                                        $tmke = $database[0]['jml'];
                                        if ($tmke == 14) {
                                            return "$tmke/14 - ".Html::a(
                                                'terpenuhi', 
                                                [
                                                    '/absen-dosen/create', 
                                                    'kelas' => $dataProvider->id, 
                                                    'dosen' => $dataProvider->dosen_id
                                                ], 
                                                [
                                                    'class' => 'btn btn-sm btn-success _modal-btn disabled',
                                                    'style' => 'margin-left: .2rem;'
                                                ]
                                            );
                                        }
                                        return "$tmke/14 - ".Html::a(
                                            '<i class="fas fa-plus"></i> Presensi', 
                                            [
                                                '/absen-dosen/create', 
                                                'kelas' => $dataProvider->id, 
                                                'dosen' => $dataProvider->dosen_id
                                            ], 
                                            [
                                                'class' => 'btn btn-sm btn-success _modal-btn',
                                                'style' => 'margin-left: .2rem;'
                                            ]
                                        );
                                    }
                                    return "0/14 - ".Html::a(
                                        '<i class="fas fa-plus"></i> Presensi', 
                                        [
                                            '/absen-dosen/create', 
                                            'kelas' => $dataProvider->id, 
                                            'dosen' => $dataProvider->dosen_id
                                        ], 
                                        [
                                            'class'=>'btn btn-sm btn-success _modal-btn',
                                            'style' => 'margin-left: .2rem;'
                                        ]
                                    );
                                },
                                'format' => 'raw',
                            ],
                        ],
                    ]); ?>
                    </div>
                <?php $i = $i + 1; ?>    
                <?php endforeach;?>
            </div>
        </div>
    </div>
</div>

<?php



Modal::begin([
    'id' => 'modal',
    'header' => 'Tambah Form Presensi',
    'class' => 'fade in'
]);
echo "<div id='content' class=''></div>";
Modal::end();

$this->registerJsFile(
    '@web/js/table-hide.js',
    ['depends' => [\yii\web\JqueryAsset::className()]]
);

$this->registerJs("
    $(function(){
        $('._modal-btn').click(function (){
            $.get($(this).attr('href'), function(data) {
              $('#modal').modal('show').find('#content').html(data)
           });
           return false;
        });
    });
");

views/absen-dosen/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\AbsenDosen */

$this->title = 'Update Absen Dosen: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Absen Dosens', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="absen-dosen-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>